fixtures:
  repositories:
    oracle_java:
      repo: 'ssh://git@stash.adaptavist.com:7999/pup/puppet-oracle_java.git'
    limits:
      repo: 'https://github.com/Adaptavist/puppet-limits'
    stdlib:
      repo: 'https://github.com/Adaptavist/puppet-stdlib'
    packages_repos:
      repo: 'ssh://git@stash.adaptavist.com:7999/pup/puppet-packages_repos.git'
    apt:
      repo: 'https://github.com/Adaptavist/puppet-apt'
    yum:
      repo: 'https://github.com/Adaptavist/puppet-yum'
    puppi:
      repo: 'https://github.com/Adaptavist/puppet-puppi'
  symlinks:
    coverity: "#{source_dir}"
